# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

# Deterministic builds; 1.0 opinionated; 2.0 loosely coupled
# Build, test, deploy - are loosely coupled
# Workflow is flow of jobs comprised of steps.
# Deterministic - run live at commit time and exact same results. Gives reproducibility and reliability.
# Version pinning - make sure that react@16.0.0 i/o react@">=16"
# Use caching

version: 2
jobs:
  one:
    docker:
      - image: circleci/node:4.8.2
    - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "Hello, again!"
      - attach_workspace:
          at: my_workspace
     - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one